server.port=8085
spring.application.name=payment-service

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/medibook_payment?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRY:86400000}

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

app.admin.userId=${ADMIN_USER_ID:1}

app.refund.window.hours=${REFUND_WINDOW_HOURS:24}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8087/api}

app.admin.userId=${ADMIN_USER_ID:1}

logging.level.com.medibook=INFO

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true