server.port=${SERVER_PORT:8761}
spring.application.name=eureka-service

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.client.service-url.defaultZone=http://${EUREKA_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.medibook=INFO
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN