server.port=8761
spring.application.name=eureka-service

# Eureka Server config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.medibook=INFO
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN
